name: Node CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start xvfb
        if: matrix.os == 'ubuntu-18.04'
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: yarn install, build, and test
        run: |
          set -x
          yarn install
          yarn prettier-check
          yarn test
        env:
          CI: true
          DISPLAY: ":99.0"
