name: Test extension
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Check format
      run: yarn fmt-check
    - name: Run tests
      run: xvfb-run -a yarn test
